MMs_ROOT = r'/home/laisong/MMs2020/MMsDATA/'
MMs_TOTAL_DATA = MMs_ROOT + 'labeled'
MMs_info_AandB = MMs_ROOT + 'M&Ms Dataset Information.xlsx'
MMs_info = MMs_ROOT + 'VENDOR_A.xlsx'
MMs_info_B = MMs_ROOT + 'VENDOR_B.xlsx'
IMG_PATH = MMs_ROOT + 'labeled/Img'
LABEL_PATH = MMs_ROOT + 'labeled/label'
MMS_2D_TRAIN = '/home/laisong/ACDC2017/mms_vendorA_2d_train'
MMS_3D_TRAIN = '/home/laisong/ACDC2017/mms_3d_train'

MMS_2D_TRAIN_B = '/home/laisong/ACDC2017/mms_vendorB_2d_train'
MMS_2D_TRAIN_AandB = '/home/laisong/ACDC2017/mms_vendorAandB_2d_train'
